services:
  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    user: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
          test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
          interval: 1s
          timeout: 5s
          retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
